### ISSUE TITLE
SAPHY 랜딩페이지의 상단 네비바를 생성한다

### ISSUE THREAD

**Issue by 2EETY** [2024-Saphy/FE#3]
## 📄 Describe
SAPHY 랜딩페이지의 상단 네비바를 생성한다

## ✅ Tasks
- [x] SAPHY-9 웹페이지 상단 네비바 구현
- [x] SAPHY-8 랜딩페이지 디자인 초안(와이어 프레임) 생성 및 검토 
- [x] SAPHY-11 Saphy에 대한 간략한 소개글 작성
